//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/myProject/MyPacket.msg.
//

#ifndef _MYPACKET_M_H_
#define _MYPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "ApplicationPacket_m.h"
// }}

/**
 * Struct generated from src/node/application/myProject/MyPacket.msg:7 by nedtool.
 */
struct data
{
    data();
    int src;
};

void doPacking(cCommBuffer *b, data& a);
void doUnpacking(cCommBuffer *b, data& a);

/**
 * Class generated from <tt>src/node/application/myProject/MyPacket.msg:11</tt> by nedtool.
 * <pre>
 * packet MyPacket extends ApplicationPacket
 * {
 *     data mydata;
 * 
 * }
 * </pre>
 */
class MyPacket : public ::ApplicationPacket
{
  protected:
    data mydata_var;

  private:
    void copy(const MyPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MyPacket&);

  public:
    MyPacket(const char *name=NULL, int kind=0);
    MyPacket(const MyPacket& other);
    virtual ~MyPacket();
    MyPacket& operator=(const MyPacket& other);
    virtual MyPacket *dup() const {return new MyPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual data& getMydata();
    virtual const data& getMydata() const {return const_cast<MyPacket*>(this)->getMydata();}
    virtual void setMydata(const data& mydata);
};

inline void doPacking(cCommBuffer *b, MyPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MyPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _MYPACKET_M_H_

